import{actions,qualities,freshState,formatClock,liveSeconds,makeEvent}from'./model.js';
const KEY='scoutline-sprint1';let state=load();let view=state.match?'live':'home';let selected=null;let timer;
function load(){try{return{...freshState(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return freshState()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function icon(name){return `<span class="icon" aria-hidden="true">${{pitch:'⌗',clock:'◷',plus:'＋',note:'✎',mic:'●',back:'‹',play:'▶',pause:'Ⅱ'}[name]||name}</span>`}
function shell(content){return `<main class="shell">${content}</main>`}
function render(){clearInterval(timer);document.querySelector('#app').innerHTML=view==='home'?home():live();bind();if(view==='live'){timer=setInterval(()=>{const e=document.querySelector('#clock');if(e)e.textContent=formatClock(liveSeconds(state.clock))},500)}}
function home(){return shell(`<header class="brand"><div class="mark">S</div><div><small>FOOTBALL INTELLIGENCE</small><h1>Scoutline</h1></div></header><section class="hero"><p class="eyebrow">MATCHDAY WORKSPACE</p><h2>See the game.<br><em>Capture the detail.</em></h2><p class="lead">Fast, private, offline-first observations built for the touchline.</p><button class="primary" id="new-match">${icon('plus')} Start live match</button></section><section><div class="section-title"><h3>Recent matches</h3><span>Stored on this device</span></div>${state.match?`<button class="match-card" id="resume"><div class="date">${new Date(state.match.createdAt).toLocaleDateString('en-GB',{day:'2-digit',month:'short'}).toUpperCase()}</div><div><b>${state.match.home} <i>vs</i> ${state.match.away}</b><span>${state.events.length} observations · ${state.players.length} players</span></div><strong>›</strong></button>`:`<div class="empty"><span>${icon('pitch')}</span><b>No matches yet</b><p>Your live sessions will appear here.</p></div>`}</section><footer>PRIVATE BY DEFAULT <span>•</span> OFFLINE READY</footer>`)}
function matchSetup(){return `<div class="modal-wrap"><form class="modal" id="match-form"><button type="button" class="close">×</button><p class="eyebrow">NEW SESSION</p><h2>Match details</h2><label>Home team<input name="home" required placeholder="Home team"></label><label>Away team<input name="away" required placeholder="Away team"></label><label>Competition<input name="competition" placeholder="League or competition"></label><button class="primary">Create match</button></form></div>`}
function live(){if(!state.match)return home();return shell(`<header class="live-head"><button class="ghost" id="home">${icon('back')}</button><div><small>${state.match.competition||'LIVE SCOUTING'}</small><h1>${state.match.home} <i>v</i> ${state.match.away}</h1></div><span class="live-pill">● LIVE</span></header><section class="scorebar"><button id="clock-toggle" class="clock-btn">${icon(state.clock.running?'pause':'play')} <b id="clock">${formatClock(liveSeconds(state.clock))}</b></button><span>${state.events.length} observations</span><button id="reset-match" class="text-btn">Finish</button></section><section class="pitch-wrap"><div class="pitch" id="pitch"><div class="half"></div><div class="circle"></div><div class="box top"></div><div class="box bottom"></div>${state.players.map(player=>`<button class="player ${selected===player.id?'selected':''}" data-player="${player.id}" style="left:${player.x}%;top:${player.y}%"><span>${player.number}</span><b>${player.name.split(' ').at(-1)}</b></button>`).join('')}</div><button class="add-player" id="add-player">${icon('plus')} Add player</button></section><section class="timeline"><div class="section-title"><h3>Timeline</h3><span>Latest first</span></div>${state.events.length?state.events.slice().reverse().map(e=>`<article class="event"><time>${formatClock(e.second)}</time><span class="quality ${e.quality.toLowerCase()}"></span><div><b>#${e.number} ${e.playerName}</b><p>${e.quality} · ${e.action}${e.detail?' · '+e.detail:''}</p>${e.note?`<blockquote>${e.note}</blockquote>`:''}</div></article>`).join(''):`<div class="empty compact"><b>No observations yet</b><p>Tap a player to record an action.</p></div>`}</section>${selected?actionPanel(state.players.find(p=>p.id===selected)):''}`)}
function playerForm(){return `<div class="modal-wrap"><form class="modal" id="player-form"><button type="button" class="close">×</button><p class="eyebrow">SQUAD</p><h2>Add a player</h2><div class="row"><label>Number<input name="number" type="number" min="1" max="99" required></label><label>Position<select name="position"><option>GK</option><option>DEF</option><option selected>MID</option><option>FWD</option></select></label></div><label>Player name<input name="name" required placeholder="Full name"></label><button class="primary">Place on pitch</button></form></div>`}
function actionPanel(p){return `<div class="panel-wrap"><form class="panel" id="action-form"><div class="handle"></div><button type="button" class="close-panel">×</button><div class="player-title"><span>${p.number}</span><div><small>${p.position}</small><h2>${p.name}</h2></div></div><fieldset><legend>Quality</legend><div class="seg quality-select">${qualities.map((q,i)=>`<label><input type="radio" name="quality" value="${q}" ${i===0?'checked':''}><span>${q}</span></label>`).join('')}</div></fieldset><fieldset><legend>Action</legend><div class="chips">${Object.keys(actions).map((a,i)=>`<label><input type="radio" name="action" value="${a}" ${i===0?'checked':''}><span>${a}</span></label>`).join('')}</div></fieldset><fieldset><legend>Detail</legend><div class="chips details">${actions.Involvement.map((d,i)=>`<label><input type="radio" name="detail" value="${d}" ${i===0?'checked':''}><span>${d}</span></label>`).join('')}</div></fieldset><label class="notes-label">Private note <span>Only on this device</span><div class="note-box"><textarea name="note" placeholder="What did you notice?"></textarea><button type="button" id="dictate" title="Dictate note">${icon('mic')}</button></div></label><button class="primary">Save observation</button></form></div>`}
function addOverlay(html){document.body.insertAdjacentHTML('beforeend',html);document.querySelector('.close')?.addEventListener('click',()=>document.querySelector('.modal-wrap').remove())}
function bind(){document.querySelector('#new-match')?.addEventListener('click',()=>{addOverlay(matchSetup());bindForms()});document.querySelector('#resume')?.addEventListener('click',()=>{view='live';render()});document.querySelector('#home')?.addEventListener('click',()=>{view='home';selected=null;render()});document.querySelector('#add-player')?.addEventListener('click',()=>{addOverlay(playerForm());bindForms()});document.querySelectorAll('[data-player]').forEach(el=>{el.addEventListener('click',()=>{selected=el.dataset.player;render()});makeDraggable(el)});document.querySelector('.close-panel')?.addEventListener('click',()=>{selected=null;render()});document.querySelector('#action-form')?.addEventListener('change',e=>{if(e.target.name==='action'){document.querySelector('.details').innerHTML=actions[e.target.value].map((d,i)=>`<label><input type="radio" name="detail" value="${d}" ${i===0?'checked':''}><span>${d}</span></label>`).join('')}});document.querySelector('#action-form')?.addEventListener('submit',saveEvent);document.querySelector('#dictate')?.addEventListener('click',dictate);document.querySelector('#clock-toggle')?.addEventListener('click',toggleClock);document.querySelector('#reset-match')?.addEventListener('click',()=>{state.clock={seconds:liveSeconds(state.clock),running:false,startedAt:null};save();view='home';render()})}
function bindForms(){document.querySelector('#match-form')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);state={...freshState(),match:{home:d.get('home'),away:d.get('away'),competition:d.get('competition'),createdAt:Date.now()}};save();view='live';document.querySelector('.modal-wrap').remove();render()});document.querySelector('#player-form')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);state.players.push({id:crypto.randomUUID(),name:d.get('name'),number:d.get('number'),position:d.get('position'),x:50,y:50});save();document.querySelector('.modal-wrap').remove();render()})}
function toggleClock(){const seconds=liveSeconds(state.clock);state.clock=state.clock.running?{seconds,running:false,startedAt:null}:{seconds,running:true,startedAt:Date.now()};save();render()}
function saveEvent(e){e.preventDefault();const d=new FormData(e.target),player=state.players.find(p=>p.id===selected);state.events.push(makeEvent({player,quality:d.get('quality'),action:d.get('action'),detail:d.get('detail'),note:d.get('note'),second:liveSeconds(state.clock)}));selected=null;save();render()}
function makeDraggable(el){let moved=false;el.addEventListener('pointerdown',e=>{moved=false;el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(!el.hasPointerCapture(e.pointerId))return;moved=true;const pitch=document.querySelector('#pitch'),r=pitch.getBoundingClientRect();const x=Math.max(6,Math.min(94,(e.clientX-r.left)/r.width*100)),y=Math.max(5,Math.min(95,(e.clientY-r.top)/r.height*100));el.style.left=x+'%';el.style.top=y+'%';const p=state.players.find(p=>p.id===el.dataset.player);p.x=x;p.y=y});el.addEventListener('pointerup',()=>{if(moved){save();selected=null;setTimeout(render,0)}})}
function dictate(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Browser dictation is not supported here. You can type your private note instead.');return}const r=new SR();r.lang='en-GB';r.interimResults=false;const b=document.querySelector('#dictate');b.classList.add('listening');r.onresult=e=>{const t=document.querySelector('[name=note]');t.value=(t.value+' '+e.results[0][0].transcript).trim()};r.onend=()=>b.classList.remove('listening');r.start()}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js'));render();
