export const qualities=['Great','Good','Reasonable','Poor'];
export const bodyParts=[{id:'left-foot',label:'Left foot',icon:'↙'},{id:'right-foot',label:'Right foot',icon:'↗'},{id:'header',label:'Header',icon:'◉'},{id:'other',label:'Other',icon:'•••'},{id:'na',label:'N/A',icon:'—'}];
export const actions=[{id:'shot',label:'Shot',icon:'◎'},{id:'pass',label:'Pass',icon:'➜'},{id:'cross',label:'Cross',icon:'⤴'},{id:'header',label:'Header',icon:'⚽'},{id:'tackle',label:'Tackle',icon:'⬟'},{id:'intercept',label:'Intercept',icon:'⌁'},{id:'dribble',label:'Dribble',icon:'〰'},{id:'clearance',label:'Clearance',icon:'◢'},{id:'save',label:'Save',icon:'✋'},{id:'foul-won',label:'Foul won',icon:'⚑'},{id:'foul',label:'Foul',icon:'◌'},{id:'other',label:'Other',icon:'•••'}];
export const areas=[{id:'goalmouth',label:'Goalmouth'},{id:'attacking-left',label:'Attacking left'},{id:'attacking-centre',label:'Attacking centre'},{id:'attacking-right',label:'Attacking right'},{id:'midfield-left',label:'Midfield left'},{id:'midfield-centre',label:'Midfield centre'},{id:'midfield-right',label:'Midfield right'},{id:'defensive-left',label:'Defensive left'},{id:'defensive-centre',label:'Defensive centre'},{id:'defensive-right',label:'Defensive right'}];
export const freshState=()=>({match:null,players:[],events:[],lineups:{home:null,away:null},clock:{seconds:0,running:false,startedAt:null}});
export function formatClock(seconds){const s=Math.max(0,Math.floor(seconds));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
export function liveSeconds(clock,now=Date.now()){return clock.seconds+(clock.running?Math.floor((now-clock.startedAt)/1000):0)}
export function makeEvent({player,teamName='',quality,bodyPart='',action,area='',note='',comment='',second}){const generatedComment=generateObservationSentence({playerName:player.name,quality,bodyPart,action,area,note});return{id:crypto.randomUUID(),playerId:player.id,playerName:player.name,number:player.number,teamName,teamSide:player.teamSide||'',quality,bodyPart,action,area,note:note.trim(),generatedComment,comment:(comment||generatedComment).trim(),second,createdAt:Date.now()}}
export function generateObservationSentence({playerName,quality,bodyPart,action,area,note=''}){const surname=playerName.trim().split(/\s+/).at(-1)||'The player';const q=(quality||'').toLowerCase();const body=bodyPart==='left-foot'?'left-footed':bodyPart==='right-foot'?'right-footed':'';const place=areaPhrase(area);const descriptor=[q,body].filter(Boolean).join(' ');const templates={shot:`${surname} produced a ${descriptor} shot${place}.`,pass:`${surname} played a ${descriptor} pass${place}.`,cross:`${surname} delivered a ${descriptor} cross${place}.`,header:`${surname} produced a ${q} header${place}.`,tackle:`${surname} made a ${q} tackle${place}.`,intercept:`${surname} made a ${q} interception${place}.`,dribble:`${surname} made a ${q} dribble${place}.`,clearance:`${surname} made a ${descriptor} clearance${place}.`,save:`${surname} made a ${q} save${place}.`,'foul-won':`${surname} did ${q} work to win a foul${place}.`,foul:`${surname} committed a ${q} foul${place}.`,other:`${surname} produced a ${q} action${place}.`};const base=(templates[action]||`${surname} produced a ${q} action${place}.`).replace(/\s+/g,' ').replace('a shot','a shot').trim();const extra=normaliseNote(note);return extra?`${base} ${extra}`:base}
function areaPhrase(area){return{goalmouth:' in the goalmouth','attacking-left':' on the left side of the attacking third','attacking-centre':' in the centre of the attacking third','attacking-right':' on the right side of the attacking third','midfield-left':' on the left side of midfield','midfield-centre':' in central midfield','midfield-right':' on the right side of midfield','defensive-left':' on the left side of the defensive third','defensive-centre':' in the centre of the defensive third','defensive-right':' on the right side of the defensive third'}[area]||''}
function normaliseNote(note){const value=note.trim();if(!value)return'';const sentence=value.charAt(0).toUpperCase()+value.slice(1);return/[.!?]$/.test(sentence)?sentence:`${sentence}.`}
const headings={team:'team',opponent:'opponent','match date':'matchDate',status:'status',source:'source','source url':'sourceUrl',published:'published','starting xi':'starters',starters:'starters',substitutes:'substitutes',subs:'substitutes',uncertainties:'uncertainties'};
export function parseLineupBlock(text){
 const result={team:'',opponent:'',matchDate:'',status:'',source:'',sourceUrl:'',published:'',starters:[],substitutes:[],uncertainties:[]};let section='';
 for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(!line)continue;const match=line.match(/^([^:]+):\s*(.*)$/);if(match&&headings[match[1].trim().toLowerCase()]){section=headings[match[1].trim().toLowerCase()];const value=match[2].trim();if(['starters','substitutes','uncertainties'].includes(section)){if(value&&value.toLowerCase()!=='none')section==='uncertainties'?result.uncertainties.push(value):result[section].push(parsePlayer(value))}else result[section]=value;continue}if(section==='starters'||section==='substitutes')result[section].push(parsePlayer(line));else if(section==='uncertainties'&&line.toLowerCase()!=='none')result.uncertainties.push(line.replace(/^[-•]\s*/,''));
 }
 result.starters=result.starters.filter(p=>p.name);result.substitutes=result.substitutes.filter(p=>p.name);return result;
}
function parsePlayer(line){const clean=line.replace(/^[-•]\s*/,'').trim();const pipe=clean.match(/^(\d{1,2}|\?)\s*[|–—-]\s*(.+)$/);const spaced=clean.match(/^(\d{1,2}|\?)\.?\s+(.+)$/);const match=pipe||spaced;return match?{number:match[1]==='?'?'':match[1],name:match[2].trim()}:{number:'',name:clean}}
export function lineupWarnings(lineup){const warnings=[];if(!lineup.team)warnings.push('Team name is missing');if(!lineup.source)warnings.push('Official source is missing');if(!lineup.sourceUrl)warnings.push('Source URL is missing');if(lineup.starters.length!==11)warnings.push(`Starting XI contains ${lineup.starters.length} players`);if(lineup.starters.some(p=>!p.number))warnings.push('One or more starters have no shirt number');if(lineup.uncertainties.length)warnings.push(`${lineup.uncertainties.length} uncertainty note${lineup.uncertainties.length===1?'':'s'} to review`);return warnings}
